Repository Bagaar/ember-graphql-mocking, pull requests merged in 2023-02, with the labels that each got.

#100 Speed up requiring `index.js` file
  index.js
Labels: enhancement

#104 Update `msw` to v1 and make it a peer dependency
  package.json
  public/mockServiceWorker.js
  yarn.lock
Labels: enhancement, breaking

#106 Update compatibility and installation section
  README.md
Labels: documentation
